version: "3.9"
services:
  mongo-single-replica:
    image: "docker.io/prismagraphql/mongo-single-replica:5.0.3"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=monty
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    container_name: mongo
