[build]
	command = "npm run build"
	publish = "dist"

[functions]
	external_node_modules = ["@clerk/fastify", "@fastify/mongodb", "@fastify/multipart", "@fastify/swagger", "@fastify/swagger-ui", "cookies", "dotenv", "fastify", "fastify-plugin", "fastify-type-provider-zod", "jsonwebtoken", "serverless-http", "zod"]
	node_bundler = "esbuild"

[[redirects]]
	from = "/api/*"
	to = "/.netlify/functions/api/:splat"
	status = 200
