[build]
	command = "npm run build"
	publish = "dist"

[functions]
	external_node_modules = ["@clerk/clerk-sdk-node", "cookies", "dotenv", "express", "helmet", "jsonwebtoken", "serverless-http", "multer"]
	node_bundler = "esbuild"

[[redirects]]
	from = "/api/*"
	to = "/.netlify/functions/api/:splat"
	status = 200
